language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    - android-29
    - extra
    
script:
    - ./gradlew assembleDebug
    
#     
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep_history: false
#   verbose: false
#   file: "./app/build/outputs/apk/debug/all-AudioDemo-debug-5.02.apk"
#   on:
#     branch: master
    